// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzqhtljrirwrjikqwffw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6cWh0bGpyaXJ3cmppa3F3ZmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDAyNjksImV4cCI6MjA1ODkxNjI2OX0.8yYdDNnIkR3FoeQyQwW9vaRYxQjMs8vJid24S6W0mOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);